### ISSUE TITLE
Errors when trying to predict single .wav file.

### ISSUE THREAD

**Issue by Varuzhan97** [siddheswarc/LID-using-CRNNs#1]
Command is:
python predict.py --model ~/Desktop/LID-using-CRNNs-master/config/pre-trained-models/CRNN_EN_DE_FR.model --input aaa.wav

Error is:
Audio to Spectrogram Error: File not found (Spectrogram conversion error)
Traceback (most recent call last):
  File "predict.py", line 47, in <module>
    predict(cli_args)
  File "predict.py", line 24, in predict
    data = np.stack(data)
  File "<__array_function__ internals>", line 6, in stack
  File "/home/varuzhan/.local/lib/python3.6/site-packages/numpy/core/shape_base.py", line 422, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

**Comment by siddheswarc** [comment]
> Command is:
> python predict.py --model ~/Desktop/LID-using-CRNNs-master/config/pre-trained-models/CRNN_EN_DE_FR.model --input aaa.wav
> 
> Error is:
> Audio to Spectrogram Error: File not found (Spectrogram conversion error)
> Traceback (most recent call last):
> File "predict.py", line 47, in
> predict(cli_args)
> File "predict.py", line 24, in predict
> data = np.stack(data)
> File "<**array_function** internals>", line 6, in stack
> File "/home/varuzhan/.local/lib/python3.6/site-packages/numpy/core/shape_base.py", line 422, in stack
> raise ValueError('need at least one array to stack')
> ValueError: need at least one array to stack

This LID tool relies on the SoX (Sound eXchange) package to convert the audio files into its corresponding Spectrogram representations. The Spectrogram conversion error means that SoX was unable to produce an image for the audio file and is an error corresponding to the SoX package. Most probable reasons for this error could be:
1. The input format was unrecognized by SoX
2. The audio codec was unrecognized by SoX
3. The input audio was corrupted
Though the audio file might play properly, SoX might still fail to process it.
A few solutions I can suggest are:
1. Try with another audio file
2. Try the _ignore length_ flag with the sox command ( `sox --ignore-length corrupted.wav fixed.wav` )
2. Use another audio processing package as an alternative to SoX (you will have to make changes in the code accordingly)
